Repository googleapis/python-firestore, pull requests merged in 2020-08, with the labels that each got.

#134 feat: add inline type hints
  google/cloud/firestore.py
  google/cloud/firestore_admin_v1/services/firestore_admin/async_client.py
  google/cloud/firestore_admin_v1/services/firestore_admin/client.py
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/base.py
  google/cloud/firestore_v1/__init__.py
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/async_batch.py
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_collection.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_query.py
  google/cloud/firestore_v1/async_transaction.py
  google/cloud/firestore_v1/base_batch.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/base_transaction.py
  google/cloud/firestore_v1/batch.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/order.py
  google/cloud/firestore_v1/query.py
  google/cloud/firestore_v1/services/firestore/transports/base.py
  google/cloud/firestore_v1/transaction.py
  google/cloud/firestore_v1/transforms.py
  google/cloud/firestore_v1/types/__init__.py
  google/cloud/firestore_v1/types/common.py
  google/cloud/firestore_v1/types/document.py
  google/cloud/firestore_v1/types/firestore.py
  google/cloud/firestore_v1/types/query.py
  google/cloud/firestore_v1/types/write.py
  google/cloud/firestore_v1/watch.py
  noxfile.py
  setup.cfg
Labels: cla: yes, do not merge

#146 fix: pytype client errors
  .gitignore
  google/cloud/firestore_v1/base_client.py
Labels: cla: yes

#145 feat: integrate limit to last
  google/cloud/firestore_v1/async_collection.py
  google/cloud/firestore_v1/async_query.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/query.py
  tests/unit/v1/test_async_collection.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_base_collection.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_query.py
Labels: cla: yes

#147 fix: async transactional
  google/cloud/firestore_v1/async_transaction.py
  tests/unit/v1/test_async_transaction.py
Labels: cla: yes

#148 feat(firestore): add client_options to base class
  google/cloud/firestore_v1/client.py
  setup.py
  tests/unit/v1/test_client.py
Labels: cla: yes

#150 feat: add client_options to base client class
  google/cloud/firestore_v1/base_client.py
  setup.py
  tests/unit/v1/test_async_client.py
  tests/unit/v1/test_client.py
Labels: cla: yes

#144 fix: some typing improvements
  google/cloud/firestore.py
  google/cloud/firestore_v1/__init__.py
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_transaction.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/base_transaction.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/transaction.py
Labels: cla: yes

#155 docs: update docs build (via synth)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  google/cloud/firestore_v1beta1/gapic/firestore_client.py
  noxfile.py
  synth.metadata
  synth.py
Labels: cla: yes

#161 tests: run systests on Kokoro
  .kokoro/build.sh
  synth.py
  tests/system/test_system.py
Labels: cla: yes

#174 docs: add document of admin client
  docs/admin_client.rst
  docs/index.rst
Labels: api: firestore, cla: yes

#178 docs: re-add changelog entries lost in V2 switch
  CHANGELOG.md
Labels: automerge, cla: yes
