Repository googleapis/python-firestore, pull requests merged in 2020-10, with the labels that each got.

#210 feat: partition queries
  google/cloud/firestore.py
  google/cloud/firestore_v1/__init__.py
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_query.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/query.py
  tests/system/test_system.py
  tests/system/test_system_async.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_base_query.py
  tests/unit/v1/test_query.py
Labels: cla: yes

#212 fix: harden version data gathering against DistributionNotFound
  google/cloud/firestore_v1/__init__.py
Labels: cla: yes

#211 chore: add samples reviewers group
  .github/CODEOWNERS
Labels: automerge, cla: yes

#205 tests: re-enable cross-language conformance tests
  Makefile_v1
  Makefile_v1beta1
  tests/unit/v1/conformance_tests.py
  tests/unit/v1/test_cross_language.py
Labels: api: firestore, cla: yes

#182 feat: add type hints for method params
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_collection.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_query.py
  google/cloud/firestore_v1/async_transaction.py
  google/cloud/firestore_v1/base_batch.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/base_transaction.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/field_path.py
  google/cloud/firestore_v1/query.py
  google/cloud/firestore_v1/transaction.py
Labels: api: firestore, cla: yes

#202 feat: add support for not-in and not-eq query operators
  google/cloud/firestore_v1/base_query.py
  tests/system/test_system.py
  tests/unit/v1/test_base_query.py
  tests/unit/v1/testdata/query-invalid-operator.json
Labels: api: firestore, cla: yes

#222 feat: add retry/timeout to manual surface
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/async_batch.py
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_collection.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_query.py
  google/cloud/firestore_v1/async_transaction.py
  google/cloud/firestore_v1/base_batch.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/base_transaction.py
  google/cloud/firestore_v1/batch.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/query.py
  google/cloud/firestore_v1/transaction.py
  tests/unit/v1/test__helpers.py
  tests/unit/v1/test_async_batch.py
  tests/unit/v1/test_async_client.py
  tests/unit/v1/test_async_collection.py
  tests/unit/v1/test_async_document.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_async_transaction.py
  tests/unit/v1/test_batch.py
  tests/unit/v1/test_client.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_document.py
  tests/unit/v1/test_query.py
  tests/unit/v1/test_transaction.py
Labels: cla: yes

#225 chore: restore coverage (almost) to 100%
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/document.py
  tests/unit/v1/test__helpers.py
  tests/unit/v1/test_async_client.py
  tests/unit/v1/test_async_document.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_client.py
  tests/unit/v1/test_document.py
  tests/unit/v1/test_order.py
Labels: automerge, cla: yes

#176 feat: improve type information
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_transaction.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/client.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/order.py
  google/cloud/firestore_v1/transaction.py
Labels: api: firestore, cla: yes

#220 fix: remove unnecessary dependency on libcst and scripts
  scripts/fixup_admin_v1_keywords.py
  scripts/fixup_firestore_admin_v1_keywords.py
  scripts/fixup_firestore_v1_keywords.py
  setup.py
Labels: cla: yes

#224 fix: add retry for 'partition_query' (via synth)
  .coveragerc
  .kokoro/docs/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  google/cloud/firestore_v1/services/firestore/async_client.py
  google/cloud/firestore_v1/services/firestore/transports/base.py
  synth.metadata
Labels: cla: yes

#231 fix: add import message via synth
  scripts/fixup_admin_v1_keywords.py
  scripts/fixup_firestore_admin_v1_keywords.py
  scripts/fixup_firestore_v1_keywords.py
  setup.py
  synth.py
Labels: automerge, cla: yes, kokoro:force-run

#234 tests: restore 100% coverage
  .coveragerc
  google/cloud/firestore_v1/base_client.py
  synth.py
Labels: cla: yes

#239 chore: repair changelog
  CHANGELOG.md
Labels: cla: yes
