Repository googleapis/python-firestore, pull requests merged in 2020-11, with the labels that each got.

#241 chore: add trove classifier to setup.py for 3.8, 3.9
  noxfile.py
  setup.py
Labels: cla: yes

#245 docs: adds UPGRADING.md, not to readme, to help inform users about migration to v2
  README.rst
  UPGRADING.md
  docs/UPGRADING.md
Labels: api: firestore, cla: yes

#248 docs: add upgrading section to index of documentation
  docs/index.rst
Labels: api: firestore, cla: yes

#254 fix: use an insecure channel under emulation
  google/cloud/firestore_v1/base_client.py
  noxfile.py
  tests/unit/v1/test_base_client.py
Labels: api: firestore, cla: yes

#253 docs: update code of conduct
  CODE_OF_CONDUCT.md
  docs/conf.py
  google/cloud/firestore_v1/services/firestore/async_client.py
  google/cloud/firestore_v1/services/firestore/transports/base.py
  noxfile.py
  synth.metadata
Labels: api: firestore, cla: yes, context: partial

#256 chore: sort exceptions properly (manual synth)
  google/cloud/firestore_admin_v1/services/firestore_admin/async_client.py
  google/cloud/firestore_admin_v1/services/firestore_admin/client.py
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/grpc.py
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/grpc_asyncio.py
  google/cloud/firestore_v1/services/firestore/async_client.py
  google/cloud/firestore_v1/services/firestore/client.py
  google/cloud/firestore_v1/services/firestore/transports/base.py
  google/cloud/firestore_v1/services/firestore/transports/grpc.py
  google/cloud/firestore_v1/services/firestore/transports/grpc_asyncio.py
  google/cloud/firestore_v1/types/document.py
  noxfile.py
  scripts/fixup_firestore_admin_v1_keywords.py
  scripts/fixup_firestore_v1_keywords.py
  synth.metadata
  tests/unit/gapic/firestore_admin_v1/test_firestore_admin.py
  tests/unit/gapic/firestore_v1/test_firestore.py
Labels: api: firestore, cla: yes

#258 tests: require 100% unit test coverage
  noxfile.py
  synth.py
Labels: api: firestore, cla: yes
