Repository googleapis/python-firestore, pull requests merged in 2020-07, with the labels that each got.

#70 refactor: create base collection class
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/collection.py
  tests/unit/v1/test_base_collection.py
  tests/unit/v1/test_collection.py
Labels: automerge, cla: yes

#79 docs(firestore): on_snapshot document changes
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/query.py
Labels: cla: yes

#83 fix(#82): Add import back to generated client
  google/cloud/firestore_v1/gapic/firestore_client.py
Labels: automerge, cla: yes

#97 chore: pin to generator version 0.26.5
  google/cloud/firestore_admin_v1/services/firestore_admin/async_client.py
  scripts/fixup_admin_v1_keywords.py
  scripts/fixup_firestore_v1_keywords.py
  scripts/fixup_keywords_v1beta1.py
  setup.py
  synth.metadata
  synth.py
  tests/unit/gapic/admin_v1/__init__.py
  tests/unit/gapic/admin_v1/test_firestore_admin.py
  tests/unit/gapic/v1/__init__.py
Labels: cla: yes

#81 refactor: create base transaction class
  google/cloud/firestore_v1/base_transaction.py
  google/cloud/firestore_v1/transaction.py
  tests/unit/v1/test_base_transaction.py
  tests/unit/v1/test_transaction.py
Labels: automerge, cla: yes

#98 fix: remove six dependency
  tests/unit/v1/test_query.py
Labels: automerge, cla: yes

#88 test: add imports into test_collections systest
  tests/system/test_system.py
Labels: api: firestore, cla: yes, type: process

#105 test: add imports into test_collections systest
  tests/system/test_system.py
Labels: cla: yes

#106 refactor: drop six package use
  google/cloud/firestore_v1/_helpers.py
  google/cloud/firestore_v1/base_collection.py
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/document.py
  google/cloud/firestore_v1/field_path.py
  google/cloud/firestore_v1/transaction.py
  tests/system/test_system.py
  tests/unit/v1/test_base_query.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_order.py
Labels: api: firestore, cla: yes, kokoro:run, type: cleanup

#112 refactor: remove async unit test nox session
  noxfile.py
  tests/unit/v1/async/__init__.py
  tests/unit/v1/test_async_batch.py
  tests/unit/v1/test_async_client.py
  tests/unit/v1/test_async_collection.py
  tests/unit/v1/test_async_document.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_async_transaction.py
Labels: cla: yes

#115 docs: fix typo in watch documentation
  google/cloud/firestore_v1/watch.py
Labels: cla: yes

#110 refactor: drop six dependency
  google/cloud/firestore_v1/async_document.py
  google/cloud/firestore_v1/async_transaction.py
Labels: cla: yes

#114 fix: constructor invalid path tests
  tests/unit/v1/test_async_collection.py
  tests/unit/v1/test_async_document.py
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_base_collection.py
  tests/unit/v1/test_base_document.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_document.py
  tests/unit/v1/test_query.py
Labels: cla: yes

#109 fix: add mocks to query get test
  tests/unit/v1/test_async_query.py
  tests/unit/v1/test_query.py
Labels: cla: yes

#120 fix: remove six dependency
  tests/unit/v1/test_async_collection.py
Labels: cla: yes

#118 feat: asyncio microgen client
  google/cloud/firestore_v1/async_client.py
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/client.py
  noxfile.py
  tests/unit/v1/test__helpers.py
  tests/unit/v1/test_async_client.py
Labels: cla: yes

#119 feat: asyncio microgen collection
  google/cloud/firestore_v1/async_collection.py
  tests/unit/v1/test_async_collection.py
Labels: cla: yes

#122 feat: asyncio microgen batch
  google/cloud/firestore_v1/async_batch.py
  tests/unit/v1/test_async_batch.py
  tests/unit/v1/test_async_collection.py
  tests/unit/v1/test_async_document.py
Labels: cla: yes

#126 fix: asyncio microgen client get_all type
  google/cloud/firestore_v1/async_client.py
  tests/unit/v1/test__helpers.py
  tests/unit/v1/test_async_client.py
  tests/unit/v1/test_async_collection.py
Labels: cla: yes

#116 feat: use `DatetimeWithNanoseconds` throughout library
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/watch.py
  setup.py
  tests/system/test_system.py
  tests/unit/v1/test_async_batch.py
  tests/unit/v1/test_base_client.py
  tests/unit/v1/test_base_document.py
  tests/unit/v1/test_batch.py
Labels: cla: yes

#129 fix: asyncio document docs
  google/cloud/firestore_v1/async_document.py
Labels: cla: yes

#123 feat: asyncio microgen transaction
  google/cloud/firestore_v1/async_transaction.py
  tests/unit/v1/test_async_transaction.py
Labels: cla: yes
