Repository googleapis/python-firestore, pull requests merged in 2020-06, with the labels that each got.

#34 feat(firestore): add v1beta1 deprecation annotation
  google/cloud/firestore_v1beta1/__init__.py
Labels: cla: yes

#57 feat: support limit to last feature
  google/cloud/firestore_v1/collection.py
  google/cloud/firestore_v1/query.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_query.py
Labels: api: firestore, cla: yes, type: feature request

#66 refactor: create base client class
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/client.py
  tests/unit/v1/test_base_client.py
  tests/unit/v1/test_client.py
Labels: automerge, cla: yes

#58 fix(firestore): use specific naming convention
  google/cloud/firestore_v1/query.py
Labels: cla: yes

#67 refactor: create base batch class
  google/cloud/firestore_v1/base_batch.py
  google/cloud/firestore_v1/batch.py
  tests/unit/v1/test_base_batch.py
  tests/unit/v1/test_batch.py
Labels: automerge, cla: yes

#68 refactor: create base document class
  google/cloud/firestore_v1/base_client.py
  google/cloud/firestore_v1/base_document.py
  google/cloud/firestore_v1/document.py
  tests/unit/v1/test_base_document.py
  tests/unit/v1/test_document.py
Labels: automerge, cla: yes

#69 refactor: create base query class
  google/cloud/firestore_v1/base_query.py
  google/cloud/firestore_v1/query.py
  tests/unit/v1/test_base_query.py
  tests/unit/v1/test_collection.py
  tests/unit/v1/test_query.py
Labels: automerge, cla: yes

#31 feat(firestore): add support of emulator to run system tests on emulator
  tests/system/test_system.py
Labels: cla: yes
