Repository googleapis/python-firestore, pull requests merged in 2021-01, with the labels that each got.

#281 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: api: firestore, cla: yes

#291 test: update conf tests
  .gitignore
  CONTRIBUTING.rst
  Makefile_v1
  tests/unit/v1/conformance_tests.py
  tests/unit/v1/testdata/query-invalid-operator.json
  tests/unit/v1/testdata/set-arrayunion-merge.json
Labels: api: firestore, automerge, cla: yes

#290 tests: add system test to verify ArrayUnion upserts
  tests/system/test_system.py
Labels: api: firestore, automerge, cla: yes

#261 docs: update intersphinx for grpc and auth
  docs/conf.py
  synth.metadata
Labels: api: firestore, cla: yes, context: full

#274 fix: remove client recv msg limit and add enums to `types/__init__.py`
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/__init__.py
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/grpc.py
  google/cloud/firestore_admin_v1/services/firestore_admin/transports/grpc_asyncio.py
  google/cloud/firestore_admin_v1/types/__init__.py
  google/cloud/firestore_v1/services/firestore/transports/__init__.py
  google/cloud/firestore_v1/services/firestore/transports/grpc.py
  google/cloud/firestore_v1/services/firestore/transports/grpc_asyncio.py
  google/cloud/firestore_v1/types/__init__.py
  synth.metadata
  tests/unit/gapic/firestore_admin_v1/test_firestore_admin.py
  tests/unit/gapic/firestore_v1/test_firestore.py
Labels: api: firestore, cla: yes, context: full
