Repository googleapis/python-firestore, pull requests merged in 2022-04, with the labels that each got.

#551 chore: set up CI on v1 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  noxfile.py
Labels: api: firestore

#552 chore: allow releases on previous majors
  .github/release-please.yml
  owlbot.py
Labels: api: firestore, size: s

#550 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  noxfile.py
  setup.py
Labels: api: firestore, size: xs
